/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthLayoutauthRegisterRouteRouteImport } from './routes/_authLayout.(auth)/register/route'
import { Route as AuthLayoutauthProfileRouteRouteImport } from './routes/_authLayout.(auth)/profile/route'
import { Route as AuthLayoutauthLoginRouteRouteImport } from './routes/_authLayout.(auth)/login/route'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthLayoutauthRegisterIndexRouteImport } from './routes/_authLayout.(auth)/register/index'
import { Route as AuthLayoutauthLoginIndexRouteImport } from './routes/_authLayout.(auth)/login/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthLayoutauthRegisterApiRouteImport } from './routes/_authLayout.(auth)/register/api'
import { Route as AuthLayoutauthLoginApiRouteImport } from './routes/_authLayout.(auth)/login/api'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutauthRegisterRouteRoute =
  AuthLayoutauthRegisterRouteRouteImport.update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutauthProfileRouteRoute =
  AuthLayoutauthProfileRouteRouteImport.update({
    id: '/(auth)/profile',
    path: '/profile',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutauthLoginRouteRoute =
  AuthLayoutauthLoginRouteRouteImport.update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutauthRegisterIndexRoute =
  AuthLayoutauthRegisterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLayoutauthRegisterRouteRoute,
  } as any)
const AuthLayoutauthLoginIndexRoute =
  AuthLayoutauthLoginIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLayoutauthLoginRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutauthRegisterApiRoute =
  AuthLayoutauthRegisterApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthLayoutauthRegisterRouteRoute,
  } as any)
const AuthLayoutauthLoginApiRoute = AuthLayoutauthLoginApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthLayoutauthLoginRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login': typeof AuthLayoutauthLoginRouteRouteWithChildren
  '/profile': typeof AuthLayoutauthProfileRouteRoute
  '/register': typeof AuthLayoutauthRegisterRouteRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/login/api': typeof AuthLayoutauthLoginApiRoute
  '/register/api': typeof AuthLayoutauthRegisterApiRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/login/': typeof AuthLayoutauthLoginIndexRoute
  '/register/': typeof AuthLayoutauthRegisterIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile': typeof AuthLayoutauthProfileRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/login/api': typeof AuthLayoutauthLoginApiRoute
  '/register/api': typeof AuthLayoutauthRegisterApiRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/login': typeof AuthLayoutauthLoginIndexRoute
  '/register': typeof AuthLayoutauthRegisterIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authLayout/(auth)/login': typeof AuthLayoutauthLoginRouteRouteWithChildren
  '/_authLayout/(auth)/profile': typeof AuthLayoutauthProfileRouteRoute
  '/_authLayout/(auth)/register': typeof AuthLayoutauthRegisterRouteRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authLayout/(auth)/login/api': typeof AuthLayoutauthLoginApiRoute
  '/_authLayout/(auth)/register/api': typeof AuthLayoutauthRegisterApiRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authLayout/(auth)/login/': typeof AuthLayoutauthLoginIndexRoute
  '/_authLayout/(auth)/register/': typeof AuthLayoutauthRegisterIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/login'
    | '/profile'
    | '/register'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/login/api'
    | '/register/api'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/login/'
    | '/register/'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/profile'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/login/api'
    | '/register/api'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/login'
    | '/register'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/_authLayout/(auth)/login'
    | '/_authLayout/(auth)/profile'
    | '/_authLayout/(auth)/register'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authLayout/(auth)/login/api'
    | '/_authLayout/(auth)/register/api'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authLayout/(auth)/login/'
    | '/_authLayout/(auth)/register/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/(auth)/register': {
      id: '/_authLayout/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutauthRegisterRouteRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/(auth)/profile': {
      id: '/_authLayout/(auth)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthLayoutauthProfileRouteRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/(auth)/login': {
      id: '/_authLayout/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutauthLoginRouteRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/(auth)/register/': {
      id: '/_authLayout/(auth)/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthLayoutauthRegisterIndexRouteImport
      parentRoute: typeof AuthLayoutauthRegisterRouteRoute
    }
    '/_authLayout/(auth)/login/': {
      id: '/_authLayout/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLayoutauthLoginIndexRouteImport
      parentRoute: typeof AuthLayoutauthLoginRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/(auth)/register/api': {
      id: '/_authLayout/(auth)/register/api'
      path: '/api'
      fullPath: '/register/api'
      preLoaderRoute: typeof AuthLayoutauthRegisterApiRouteImport
      parentRoute: typeof AuthLayoutauthRegisterRouteRoute
    }
    '/_authLayout/(auth)/login/api': {
      id: '/_authLayout/(auth)/login/api'
      path: '/api'
      fullPath: '/login/api'
      preLoaderRoute: typeof AuthLayoutauthLoginApiRouteImport
      parentRoute: typeof AuthLayoutauthLoginRouteRoute
    }
  }
}

interface AuthLayoutauthLoginRouteRouteChildren {
  AuthLayoutauthLoginApiRoute: typeof AuthLayoutauthLoginApiRoute
  AuthLayoutauthLoginIndexRoute: typeof AuthLayoutauthLoginIndexRoute
}

const AuthLayoutauthLoginRouteRouteChildren: AuthLayoutauthLoginRouteRouteChildren =
  {
    AuthLayoutauthLoginApiRoute: AuthLayoutauthLoginApiRoute,
    AuthLayoutauthLoginIndexRoute: AuthLayoutauthLoginIndexRoute,
  }

const AuthLayoutauthLoginRouteRouteWithChildren =
  AuthLayoutauthLoginRouteRoute._addFileChildren(
    AuthLayoutauthLoginRouteRouteChildren,
  )

interface AuthLayoutauthRegisterRouteRouteChildren {
  AuthLayoutauthRegisterApiRoute: typeof AuthLayoutauthRegisterApiRoute
  AuthLayoutauthRegisterIndexRoute: typeof AuthLayoutauthRegisterIndexRoute
}

const AuthLayoutauthRegisterRouteRouteChildren: AuthLayoutauthRegisterRouteRouteChildren =
  {
    AuthLayoutauthRegisterApiRoute: AuthLayoutauthRegisterApiRoute,
    AuthLayoutauthRegisterIndexRoute: AuthLayoutauthRegisterIndexRoute,
  }

const AuthLayoutauthRegisterRouteRouteWithChildren =
  AuthLayoutauthRegisterRouteRoute._addFileChildren(
    AuthLayoutauthRegisterRouteRouteChildren,
  )

interface AuthLayoutRouteChildren {
  AuthLayoutauthLoginRouteRoute: typeof AuthLayoutauthLoginRouteRouteWithChildren
  AuthLayoutauthProfileRouteRoute: typeof AuthLayoutauthProfileRouteRoute
  AuthLayoutauthRegisterRouteRoute: typeof AuthLayoutauthRegisterRouteRouteWithChildren
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutauthLoginRouteRoute: AuthLayoutauthLoginRouteRouteWithChildren,
  AuthLayoutauthProfileRouteRoute: AuthLayoutauthProfileRouteRoute,
  AuthLayoutauthRegisterRouteRoute:
    AuthLayoutauthRegisterRouteRouteWithChildren,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DemoStoreRoute: DemoStoreRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
